name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'        # evita loops por el deploy
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Si no usas package-lock.json, fijamos versiones web compatibles
      - name: Pin Expo Web deps (React 18.2)
        run: |
          npm pkg set "dependencies.react=18.2.0"
          npm pkg set "dependencies.react-dom=18.2.0"
          npm pkg set "overrides.react=18.2.0"
          npm pkg set "overrides.react-dom=18.2.0"
          npm pkg set "dependencies.react-native-web=0.19.10"
          npm pkg set "dependencies.@expo/metro-runtime=~3.2.3"

      - name: Install
        run: npm install --no-audit --no-fund --omit=optional

      - name: Lint
        run: npm run lint || echo "No lint script"

      - name: Test
        run: npm test
