name: Build & Deploy Expo Web to gh-pages

on:
  push:
    branches:
      - '**'          # todas las ramas
    branches-ignore:
      - gh-pages      # evita loops por el branch de Pages
    paths-ignore:
      - 'dist/**'
      - 'docs/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1) Checkout con LFS
      - uses: actions/checkout@v4
        with:
          lfs: true

      # 2) Node + cache npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # 3) Install deps
      - name: Install
        run: npm ci --no-audit --no-fund

      # 4) (Higiene) borra claves sueltas que puedan confundir a Expo
      - name: Clean stray Expo keys in package.json
        run: |
          node - <<'NODE'
          const fs=require('fs');
          const p=JSON.parse(fs.readFileSync('package.json','utf8'));
          delete p.icon; delete p.web; delete p.splash;
          fs.writeFileSync('package.json', JSON.stringify(p,null,2));
          console.log('package.json cleaned');
          NODE

      # 5) Genera assets CI válidos y escribe app.json limpio (override para este build)
      - name: Generate CI assets and app.json
        run: |
          sudo apt-get update && sudo apt-get install -y imagemagick
          mkdir -p assets
          # icon 1024x1024 transparente
          convert -size 1024x1024 xc:none PNG32:assets/icon.png
          cp assets/icon.png assets/icon.local.png
          # favicon 512x512 derivado
          convert assets/icon.png -resize 512x512 PNG32:assets/favicon.png
          cp assets/favicon.png assets/favicon.local.png
          # splash 2048x2048 blanco
          convert -size 2048x2048 xc:white PNG32:assets/splash.png
          cp assets/splash.png assets/splash.local.png

          # app.json minimal apuntando a estos assets
          cat > app.json <<'JSON'
          {
            "expo": {
              "name": "rn-sudoku",
              "slug": "rn-sudoku",
              "platforms": ["ios", "android", "web"],
              "userInterfaceStyle": "automatic",
              "icon": "./assets/icon.png",
              "splash": {
                "image": "./assets/splash.png",
                "resizeMode": "contain",
                "backgroundColor": "#ffffff"
              },
              "web": {
                "bundler": "metro",
                "favicon": "./assets/favicon.png",
                "build": { "publicPath": "/rn-sudoku/" }
              }
            }
          }
          JSON

      # 6) (Opcional) verifica que sean PNG reales y no punteros LFS
      - name: Verify assets are real PNGs
        run: |
          git lfs ls-files || true
          file assets/*.png || true

      # 7) Desactiva caché de image-utils por si quedó algo viejo
      - name: Disable image utils cache
        run: echo "EXPO_IMAGE_UTILS_NO_CACHE=1" >> $GITHUB_ENV

      # 8) Build Expo Web -> dist/
      - name: Build web (to dist/)
        run: npm run build:web
        env:
          EXPO_APP_JSON: app.json

