name: CI — Expo Web (all branches & PR)

on:
  push:
    branches: ["**"]
    branches-ignore:
      - gh-pages
    paths-ignore:
      - "dist/**"
      - "docs/**"
  pull_request:
    branches: ["**"]
    paths-ignore:
      - "dist/**"
      - "docs/**"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1) Checkout con LFS (por si hay PNGs en Git LFS)
      - uses: actions/checkout@v4
        with:
          lfs: true

      # 2) Node + cache npm
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      # 3) Instalar deps
      - name: Install
        run: npm ci --no-audit --no-fund

      # 4) Higiene: elimina claves Expo sueltas en package.json (usar sólo app.json)
      - name: Clean stray Expo keys in package.json
        run: |
          node - <<'NODE'
          const fs=require('fs');
          const p=JSON.parse(fs.readFileSync('package.json','utf8'));
          delete p.icon; delete p.web; delete p.splash;
          fs.writeFileSync('package.json', JSON.stringify(p,null,2));
          console.log('package.json cleaned');
          NODE

      # 5) Generar assets válidos + app.json mínimo (para evitar CRC)
      - name: Generate CI assets and app.json
        run: |
          sudo apt-get update && sudo apt-get install -y imagemagick
          mkdir -p assets
          # icon 1024x1024 transparente
          convert -size 1024x1024 xc:none PNG32:assets/icon.png
          cp assets/icon.png assets/icon.local.png
          # favicon 512x512
          convert assets/icon.png -resize 512x512 PNG32:assets/favicon.png
          cp assets/favicon.png assets/favicon.local.png
          # splash 2048x2048 blanco
          convert -size 2048x2048 xc:white PNG32:assets/splash.png
          cp assets/splash.png assets/splash.local.png

          # app.json limpio con publicPath del subpath
          cat > app.json <<'JSON'
          {
            "expo": {
              "name": "rn-sudoku",
              "slug": "rn-sudoku",
              "platforms": ["ios", "android", "web"],
              "userInterfaceStyle": "automatic",
              "icon": "./assets/icon.png",
              "splash": {
                "image": "./assets/splash.png",
                "resizeMode": "contain",
                "backgroundColor": "#ffffff"
              },
              "web": {
                "bundler": "metro",
                "favicon": "./assets/favicon.png",
                "build": { "publicPath": "/rn-sudoku/", "pwa": false }
              }
            }
          }
          JSON

      # 6) Preferir Sharp (evita Jimp y CRC)
      - name: Enable sharp image pipeline
        run: npm i -D sharp sharp-cli

      - name: Check sharp presence
        run: node -e "require.resolve('sharp');console.log('sharp present ✅')"

      # 7) Evitar cachés previas de image-utils
      - name: Disable image utils cache
        run: echo "EXPO_IMAGE_UTILS_NO_CACHE=1" >> $GITHUB_ENV

      # 8) Build Expo Web -> dist/
      - name: Build web (to dist/)
        run: npm run build:web
        env:
          EXPO_APP_JSON: app.json

      - name: Rewrite absolute paths for GH Pages + ship favicon
        env:
          SITE_BASE: /rn-sudoku
        run: |
            set -e
            # 1) Favicon dentro del subpath
            SRC="assets/favicon.png"; [ -f "$SRC" ] || SRC="assets/icon.png"
            cp "$SRC" dist/favicon.png || true
            sudo apt-get update && sudo apt-get install -y imagemagick
            convert "$SRC" -define icon:auto-resize=256,128,64,48,32,16 dist/favicon.ico || true

            # 2) Reescritura masiva en todo dist:
            #    "/_expo/..."  -> "/rn-sudoku/_expo/..."
            #    También arregla <link rel="icon"> a /rn-sudoku/favicon.ico
            find dist -type f \( -name '*.html' -o -name '*.js' -o -name '*.json' -o -name '*.css' \) -print0 | xargs -0 sed -i \
              -e "s:\"/_expo/:\"${SITE_BASE}/_expo/:g" \
              -e "s:'/_expo/:'${SITE_BASE}/_expo/:g" \
              -e "s:href=[\"']/favicon\\.ico[\"']:href=\"${SITE_BASE}/favicon.ico\":g"

            # 3) Asegura el <link rel="icon"> también en index/404 (por si no existía)
            node - <<'NODE'
            const fs=require('fs'); const SITE_BASE=process.env.SITE_BASE||'';
            for (const f of ['dist/index.html','dist/404.html']) {
              if (!fs.existsSync(f)) continue;
              let html=fs.readFileSync(f,'utf8');
              html=html.replace(/<link[^>]*rel=["']icon["'][^>]*>\s*/gi,'');
              if (html.includes('</head>')) {
                html=html.replace('</head>', `  <link rel="icon" href="${SITE_BASE}/favicon.ico"/>\n</head>`);
              }
              fs.writeFileSync(f, html);
            }
            NODE

            # 4) Debug: muestra líneas con _expo y favicon tras parcheo
            grep -nE '(_expo\/static\/js|rel="icon")' dist/index.html || true


      # 10) Publicar artefacto para revisar en PRs
      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: dist
          if-no-files-found: warn
