name: Build Expo Web to /docs (Pages from branch)

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
              fetch-depth: 0  # Necesario para gh-pages 
              lfs: true  # Si usas Git LFS
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      # 3) Install deps
      - name: Install
        run: npm ci --no-audit --no-fund

      - name: Make clean PNG assets for CI
        run: |
            mkdir -p assets
            BASE64_PNG="iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAObl+Q8AAAAASUVORK5CYII="
            echo "$BASE64_PNG" | base64 -d > assets/icon.png
            cp assets/icon.png assets/favicon.png
            cp assets/icon.png assets/splash.png

      - name: Check assets
        run: |
            git lfs ls-files || true
            ls -l assets
            file assets/*.png || true


      - name: Build web (to dist/)
        run: npm run build:web
        env:
          EXPO_APP_JSON: app.json

      - name: SPA fallback & nojekyll
        run: |
            echo '<!DOCTYPE html><html><head><meta charset="utf-8"><meta http-equiv="refresh" content="0; url=./index.html"></head><body></body></html>' > dist/404.html
            touch dist/.nojekyll
            rm -f dist/sw.js dist/registerSW.* || true

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true

