name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Pin react versions (18.2)
        run: |
          npm pkg set "dependencies.react=18.2.0"
          npm pkg set "dependencies.react-dom=18.2.0"
          npm pkg set "overrides.react=18.2.0"
          npm pkg set "overrides.react-dom=18.2.0"
          npm pkg set "dependencies.react-native-web=0.19.10"

      - name: Install deps (no lockfile)
        run: npm install --no-audit --no-fund --omit=optional

      - name: Build web
        run: npm run web:build:repo

      - name: SPA fallback (404.html)
        run: cp dist/index.html dist/404.html

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: gh-pages
