name: Build Expo Web to /docs (Pages from branch)

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Quita este bloque si tienes package-lock.json y usas npm ci
      - name: Pin Expo Web deps (React 18.2)
        run: |
          npm pkg set "dependencies.react=18.2.0"
          npm pkg set "dependencies.react-dom=18.2.0"
          npm pkg set "overrides.react=18.2.0"
          npm pkg set "overrides.react-dom=18.2.0"
          npm pkg set "dependencies.react-native-web=0.19.10"
          npm pkg set "dependencies.@expo/metro-runtime=~3.2.3"

      - name: Install
        run: npm install --no-audit --no-fund --omit=optional

      # Genera un app.ci.json con assets válidos para evitar CRC de Jimp
      - name: Make CI config and assets
        run: node scripts/ci-make-config.js

      - name: Make CI config and assets
        run: node scripts/ci-make-config.js

      - name: Build web (to dist/)
        run: npx expo export --platform web --output-dir dist
        env:
          EXPO_APP_JSON: app.ci.json

      # (Opcional) elimina service worker para evitar caches viejos
      - name: Remove service worker (optional)
        run: |
          rm -f dist/sw.js || true
          rm -f dist/registerSW.* || true

      # Copia a /docs y desactiva Jekyll
      - name: Prepare /docs for Pages
        run: |
            rm -rf docs
            mkdir -p docs
            cp -r dist/* docs/
      - name: Disable Jekyll
        run: echo > docs/.nojekyll

      # DEBUG: asegúrate que base está inyectada y rutas correctas
      - name: Show index head (debug)
        run: |
            head -n 40 docs/index.html
            echo "---- first scripts ----"
            grep -oE '<script[^>]+src="[^"]+"' -m 5 docs/index.html || true
            echo "---- first links ----"
            grep -oE '<link[^>]+href="[^"]+"' -m 5 docs/index.html || true

      # Inyecta <base href="/rn-sudoku/"> y crea 404.html
      - name: Patch base and SPA 404
        run: |
          node scripts/patch-base.js dist /rn-sudoku
          node scripts/make-404.js dist

      # (Opcional) elimina service workers para evitar cache viejo
      - name: Remove service worker (optional)
        run: |
          rm -f dist/sw.js || true
          rm -f dist/registerSW.* || true

      # Copia a /docs para Pages
      - name: Prepare /docs for Pages
        run: |
          rm -rf docs
          mkdir -p docs
          cp -r dist/* docs/

      # Evita Jekyll
      - name: Disable Jekyll
        run: echo > docs/.nojekyll

      # Verifica que <base> está realmente inyectado (debug)
      - name: Show index head (debug)
        run: head -n 30 docs/index.html

      # Commit a main
      - name: Commit docs to main
        uses: EndBug/add-and-commit@v9
        with:
          add: "docs"
          message: "[skip ci] build: export web to /docs"
          default_author: github_actions
