name: Build & Deploy Expo Web to gh-pages

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'dist/**'
      - 'docs/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install
        run: npm ci --no-audit --no-fund

      - name: Build web (to dist/)
        run: npm run build:web
        env:
          # Usa esto solo si de verdad generas un app.ci.json en scripts
          EXPO_APP_JSON: app.json

      - name: SPA fallback & nojekyll
        run: |
          echo '<!DOCTYPE html><html><head><meta charset="utf-8"><meta http-equiv="refresh" content="0; url=./index.html"></head><body></body></html>' > dist/404.html
          touch dist/.nojekyll
          # (Opcional) borrar SW para evitar cache viejo
          rm -f dist/sw.js dist/registerSW.* || true

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true
