name: Build Expo Web to /docs (Pages from branch)

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Si NO tienes package-lock.json, deja este bloque
      - name: Pin Expo Web deps (React 18.2)
        run: |
          npm pkg set "dependencies.react=18.2.0"
          npm pkg set "dependencies.react-dom=18.2.0"
          npm pkg set "overrides.react=18.2.0"
          npm pkg set "overrides.react-dom=18.2.0"
          npm pkg set "dependencies.react-native-web=0.19.10"
          npm pkg set "dependencies.@expo/metro-runtime=~3.2.3"

      - name: Install
        run: npm install --no-audit --no-fund --omit=optional

      # 🔧 Genera app.ci.json y assets válidos
      - name: Make CI config and assets
        run: node scripts/ci-make-config.js

      # 🏗️ Exporta usando el config de CI (evita PNGs corruptos del repo)
      - name: Build web (to dist/)
        run: npx expo export --platform web --config app.ci.json --output-dir dist

      # 🔁 Ajusta base para Pages bajo /rn-sudoku y crea 404
      - name: Patch base and 404
        run: |
          node scripts/patch-base.js dist /rn-sudoku
          node scripts/make-404.js dist

      # 📁 Copia a /docs para Pages from branch
      - name: Prepare /docs for Pages
        run: |
          rm -rf docs
          mkdir -p docs
          cp -r dist/* docs/

      - name: Disable Jekyll
        run: echo > docs/.nojekyll

      - name: Commit docs to main
        uses: EndBug/add-and-commit@v9
        with:
          add: "docs"
          message: "[skip ci] build: export web to /docs"
          default_author: github_actions
