name: Build Expo Web to /docs (Pages from branch)

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Quita este bloque si tienes package-lock.json y usas npm ci
      - name: Pin Expo Web deps (React 18.2)
        run: |
          npm pkg set "dependencies.react=18.2.0"
          npm pkg set "dependencies.react-dom=18.2.0"
          npm pkg set "overrides.react=18.2.0"
          npm pkg set "overrides.react-dom=18.2.0"
          npm pkg set "dependencies.react-native-web=0.19.10"
          npm pkg set "dependencies.@expo/metro-runtime=~3.2.3"

      - name: Install
        run: npm install --no-audit --no-fund --omit=optional

      # Genera un app.ci.json con assets válidos para evitar CRC de Jimp
      - name: Make CI config and assets
        run: node scripts/ci-make-config.js

      - name: Make CI config and assets
        run: node scripts/ci-make-config.js

      - name: Install gh-pages
        run: npm install --save-dev gh-pages

      - name: Build web (to dist/)
        run: npm run deploy
        env:
          EXPO_APP_JSON: app.ci.json

      # (Opcional) elimina service worker para evitar caches viejos
      - name: Remove service worker (optional)
        run: |
          rm -f dist/sw.js || true
          rm -f dist/registerSW.* || true

      # Copia a /docs y desactiva Jekyll
      - name: Disable Jekyll
        run: echo > docs/.nojekyll


      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Path to your built web files

      # (Opcional) elimina service workers para evitar cache viejo
      - name: Remove service worker (optional)
        run: |
          rm -f dist/sw.js || true
          rm -f dist/registerSW.* || true

      # Evita Jekyll
      - name: Disable Jekyll
        run: echo > dist/.nojekyll

      # Verifica que <base> está realmente inyectado (debug)
      - name: Show index head (debug)
        run: head -n 30 dist/index.html

