name: Build Expo Web to /docs (Pages from branch)

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'   # evita que el commit del propio deploy dispare de nuevo
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Si no usas package-lock.json, fijamos versiones web compatibles
      - name: Pin Expo Web deps (React 18.2)
        run: |
          npm pkg set "dependencies.react=18.2.0"
          npm pkg set "dependencies.react-dom=18.2.0"
          npm pkg set "overrides.react=18.2.0"
          npm pkg set "overrides.react-dom=18.2.0"
          npm pkg set "dependencies.react-native-web=0.19.10"
          npm pkg set "dependencies.@expo/metro-runtime=~3.2.3"

      - name: Install
        run: npm install --no-audit --no-fund --omit=optional

      - name: Build web to docs/
        run: npm run web:build:docs
        # package.json debe tener:
        # "web:build:docs": "expo export --platform web --output-dir docs"

      # 🔁 SOLO para repos bajo subruta (p. ej. /rn-sudoku/)
      - name: Inject <base> and SPA fallback
        run: |
          sed -i 's|<head>|<head><base href="/rn-sudoku/">|g' docs/index.html
          cp docs/index.html docs/404.html

      # Desactiva Jekyll en Pages
      - name: Disable Jekyll
        run: echo > docs/.nojekyll

      # Commit de /docs a main (evita loop con [skip ci])
      - name: Commit docs to main
        uses: EndBug/add-and-commit@v9
        with:
          add: "docs"
          message: "[skip ci] build: export web to /docs"
          default_author: github_actions
