name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm ci || npm install
      - name: Fix assets for CI (patch app.json)
        run: node scripts/ci-fix-assets.js

      - name: Build web (to dist/)
        run: npm run web:build:pages
        # Ej.: "web:build:pages": "expo export --platform web --output-dir dist && node scripts/patch-base.js dist /rn-sudoku && node scripts/make-404.js dist"

      - name: Prepare /docs for Pages
        run: |
          rm -rf docs
          mkdir -p docs
          cp -r dist/* docs/

      - name: Disable Jekyll
        run: echo > docs/.nojekyll

      - name: Commit docs to main
        uses: EndBug/add-and-commit@v9
        with:
          add: "docs"
          message: "[skip ci] build: export web to /docs"
          default_author: github_actions

