name: RN Android Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  android:
    runs-on: ubuntu-latest
    env:
      JAVA_HOME: /usr/lib/jvm/temurin-17-jdk
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
      GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx3g -XX:+UseParallelGC -Dkotlin.daemon.jvm.options=-Xmx2g"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('android/**/gradle-wrapper.properties','android/**/build.gradle','android/**/gradle.properties') }}

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute gradlew
        run: chmod +x android/gradlew

      - name: Build
        working-directory: android
        run: ./gradlew clean :app:assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: android/app/build/outputs/apk/release/*.apk
