name: RN iOS Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  ios:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Install Pods
        working-directory: ios
        run: |
          sudo gem install cocoapods -N
          pod repo update
          pod install

      - name: Build (Debug)
        working-directory: ios
        run: |
          xcodebuild -workspace YourApp.xcworkspace \
            -scheme YourApp \
            -sdk iphonesimulator \
            -configuration Debug \
            -derivedDataPath build \
            CODE_SIGNING_ALLOWED=NO

      - name: Upload build logs
        uses: actions/upload-artifact@v4
        with:
          name: ios-derived-data
          path: ios/build
